### ISSUE TITLE
Is there a way to specify the 'slugify' function?

### ISSUE THREAD

**Issue by twang2218** [bubkoo/hexo-toc#10]
I have some problems with Chinese headings, I hope that it's possible to use some slugify functions other than simple `uslug`, such as https://github.com/andyhu/node-transliteration.

Is there anyway to do that? or should I create a PR to add a such option in `hexo-toc`?

**Comment by bubkoo** [comment]
可以搞一个在 `_config.yml` 中增加一个选项来做这个事，欢迎提 PR

**Comment by bubkoo** [comment]
@twang2218

**Comment by twang2218** [comment]
@bubkoo OK, I will do it.
