### ISSUE TITLE
Anchor symbol problems

### ISSUE THREAD

**Issue by Cabbagec** [bubkoo/hexo-toc#16]
Double quotes are added to anchor symbol, and I think it is not intended. While HTML bookmark on the symbol is not working properly, for a missing hashtag ("#") in the href. 

Say,
>`# Heading`

becomes
>`"#" Heading`

And, click on the anchor symbol, link href becomes `/Heading`, which is supposed to be `/#Heading`, making browser goes to 404 page.

After rolling back to v1.0.4, everything works fine. Thanks!

**Comment by bubkoo** [comment]
@Cabbagec  I have tested the latest version of v1.0.8, which act ok.

**Comment by Cabbagec** [comment]
@bubkoo Cool, I'm going to go double check. Maybe that's the problem of my theme.

**Comment by zh-impact** [comment]
I have the problem too. 

My hexo version is 3.2.2, and use the default theme landscape

the symbol renderd with qutoes "#", and the href with a have not leading `#`.

which is like that:

```html
<h2 id="ji-ben-yu-fa-pian">
    <a href="ji-ben-yu-fa-pian" class="header-anchor">"#"</a>
    <a href="#基本语法篇" class="headerlink" title="基本语法篇"></a>
    基本语法篇
</h2>
```
