### ISSUE TITLE
can hexo-toc render as treeView?

### ISSUE THREAD

**Issue by geosmart** [bubkoo/hexo-toc#5]
can hexo-toc render as treeView,just as :

<pre>
1.  title1
    1.1. title1.1
    1.2. title1.2
    1.3. title1.3
2. title2
    2.1. title2.1
    2.2. title2.2
    2.3. title2.3
</pre>

now it is just render as a list
[demo](http://geosmart.github.io/2015/06/28/mongodb%E5%AE%89%E8%A3%85%E8%84%9A%E6%9C%AC/)

**Comment by geosmart** [comment]
i just try add   `<%- toc(post.content) %>` to article.ejs
now it has the  toc number ,but it generate toc in every post

**Comment by bubkoo** [comment]
Place a placeholder `<!-- toc -->` in your markdown file when and where needed.

**Comment by bubkoo** [comment]
list can be rendered as tree with css style.

**Comment by geosmart** [comment]
thanks,and now i use the theme  "next", it have the toc plugin and without any config
