### ISSUE TITLE
toc plugin cause errors

### ISSUE THREAD

**Issue by ghost** [bubkoo/hexo-toc#6]
Hi, first thx for the development of hexo-toc, however recently i found toc has confict with my blog. With its being installed, i cannot generate the files via hexo. the error is : Cannot read property 'constructor' of null and Cannot read property '0' of undefined
![qq 20150807040150](https://cloud.githubusercontent.com/assets/13208573/9122024/e5487b7a-3cb8-11e5-9d19-8f25ac85a716.png)
If needed, i can provide the problem folder.
best rgrds
haocheng

**Comment by bubkoo** [comment]
email me whit the error `.md` file.
